version: '3'

services: 
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
    server:
        restart: always
        build: 
            context: .
            dockerfile: DockerFile
        ports:
            - "3000:3000"
        links: 
            - mongo